# Generated by Django 4.1.1 on 2022-09-27 16:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=50, validators=[django.core.validators.MinLengthValidator(2, '')], verbose_name='First name')),
                ('last_name', models.CharField(db_column='last_name', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'min length <last name> last name field value less than 2 letters')], verbose_name='last_name')),
                ('birthday', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
    ]
