# Generated by Django 4.1.1 on 2022-09-29 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(error_messages={'min length': '"last name" field values less than 2 symbols'}, max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='last_name'),
        ),
        migrations.AlterModelTable(
            name='students',
            table='students_table',
        ),
    ]
