# Generated by Django 4.1.1 on 2022-09-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_birthday_alter_students_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
