# Generated by Django 4.1.1 on 2022-09-29 16:30

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_students_student_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254, validators=[students.validators.ValidEmailDomain]),
            preserve_default=False,
        ),
    ]
