# Generated by Django 4.1.1 on 2022-09-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
